### ISSUE TITLE
Installing Plugin using .jar file

### ISSUE THREAD

**Issue by jarosado0911** [c2m2/VRL-VRN-Generator#2]
I downloaded the release using the ```Release``` tab. 
I unzipped the and started VRL studio to load the plugin. 
I used the ```Install Plugin``` tab and searched for the ```VRL-VRN-Generator```, no error message appeared
I restarted ```VRL-Studio``` and I when I tried to open the example project in ```ex``` I get 
![image](https://user-images.githubusercontent.com/57325500/111677992-29ec7900-87f6-11eb-90a4-ff7bf5da8d37.png)

I tried loading it anyway but I get:
![image](https://user-images.githubusercontent.com/57325500/111678219-6e781480-87f6-11eb-8544-375445a00c7a.png)

I also attached the output in the VRL log I get.
[vrllog.txt](https://github.com/c2m2/VRL-VRN-Generator/files/6166476/vrllog.txt)

I'm sorry this happen seems like everthing I try goes to :poop:  :disappointed:

**Comment by stephanmg** [comment]
Oh, wait a minute, that's okay, you have the pre-release v0.0.1 and the template project version seems to be v0.0.0.2. I'll correct this issue.

**Comment by stephanmg** [comment]
Project version updated for the example in the `ex` folder. Feel free to reopen if error persists with the Github prerelease v.0.0.1.
