### ISSUE TITLE
Still receiving one error

### ISSUE THREAD

**Issue by jarosado0911** [c2m2/VRL-VRN-Generator#6]
I tried the fixWin branch and follow all the steps; however, I am receiving the error in vrl
![image](https://user-images.githubusercontent.com/57325500/111855819-22fc5e00-88fd-11eb-8d5d-eacad34caa53.png)

**Comment by stephanmg** [comment]
PR #7 fixes this. Try a `git pul`  from either `master` or `fixWin` branch. Open if error persists.

**Comment by jarosado0911** [comment]
I git pull from master and tried again. I am receiving:
![image](https://user-images.githubusercontent.com/57325500/112767307-fa9eee80-8fe3-11eb-99bc-e6c358dc54f1.png)

I also tried the release and I receive the same error

**Comment by stephanmg** [comment]
Did you check if the file is in the path?

**Comment by stephanmg** [comment]
@jarosado0911 release v0.0.1 should fix this issue. Open if error persists please.

**Comment by jarosado0911** [comment]
I checked that 0-2a.CNG.vrn is in the path, it is 😃 
still getting that message ```Copying file from <C:\....> ```

**Comment by stephanmg** [comment]
Did you try release v0.0.3? And could you please start VRL-Studio from a command prompt / terminal? There should be additional debug output be available.

**Comment by stephanmg** [comment]
@jarosado0911 release v0.0.4 should fix this finally.
