### ISSUE TITLE
Missing File Separators

### ISSUE THREAD

**Issue by jarosado0911** [c2m2/VRL-VRN-Generator#9]
When I press start, it will generate the ```pipeline_vr.sh``` script in the ```.vrl``` folder; however the BINARY field in the .sh script is always being set without file separators
```
BINARY=C:Usersjarosug4binugshell.exe
```

**Comment by stephanmg** [comment]
Commit #41792694aed8e7606870bc379cb34795fb940fbc should fix this issue. Let me know how it goes.

**Comment by jarosado0911** [comment]
Okay, I git pulled, and it is still giving the same error; however, the ```BINARY``` field is correct this time and the other ```ugshell.exe``` calls are correct this time in the ```pipeline_vr.sh```

**Comment by stephanmg** [comment]
@jarosado0911 try to do a `git pull` on the master branch. The commit db0407724110ba4baba0b117de0242b42f4af6a1 should finally fix your problems with the path separator character on Windows.

**Comment by stephanmg** [comment]
Looks like `getopts` is not guaranteed to be available on all Windows WSL devices. I accommodated for this.

**Comment by stephanmg** [comment]
Final fix in release v0.0.6.
